---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE}
library(RPostgreSQL)
library(reshape2)
library(ggplot2)
```

```{r results='hide'}
# connect to the database
con <- dbConnect(dbDriver("PostgreSQL"), 
                 dbname = "postgres",
                 host = "localhost", 
                 port = 5432,
                 user = "postgres", 
                 password = "apassword")

# get the hourly weather for Arlington
query = "SELECT datetime, sensor1, sensor2, sensor3
        FROM apartment_fridge"

# store query results in a dataframe 
df <- dbGetQuery(con, query)

# disconnect from the database
dbDisconnect(con)
```
```{r}
head(df)
```


```{r}
# filter df to one day
df <- subset(df, datetime > "2018-01-25" & datetime < "2018-01-26")
```

```{r}
# rename variables
names(df) <- c("datetime", "room", "freezer", "fridge")
```

```{r}
# transform dataset
df.long <- melt(df, id=c("datetime"))
```

```{r}
# rename variables
names(df.long) <- c("datetime", "location", "temperature")
```

```{r}
# inspect the df
str(df.long)
```




```{r}
# plot values over time
ggplot(data = df.long) +
  geom_point(mapping = aes(x = datetime, y = temperature, color = location))
```

